/* eslint-disable @typescript-eslint/no-unused-vars */
import {
  copilotOutputSchema,
  detectionOutputSchema,
  diagnosisOutputSchema,
  escalationOutputSchema,
  financeOutputSchema,
  learningOutputSchema,
  orchestratorOutputSchema,
  recoveryOutputSchema,
  riskOutputSchema,
} from './schemas';
import type { AgentDefinition } from './types';

const empty =
  <T>(schema: { parse: (value: unknown) => T }) =>
  (_context: unknown, _reason: string) =>
    schema.parse({
      confidence: 0,
      findings: [],
      diagnoses: [],
      recommendations: [],
      assessments: [],
      amounts: [],
      reviews: [],
      observations: [],
      answer: 'No safe recommendation is available.',
      citations: [],
      suggestedActions: [],
      objective: 'No executable objective',
      selectedAgents: [],
      policyCheckRequired: true,
      riskGateRequired: true,
      approvalRequired: true,
      executionAllowed: false,
      summary: 'No safe financial conclusion is available.',
    });

export const agentDefinitions: Record<string, AgentDefinition<unknown>> = {
  detection: {
    name: 'detection',
    responsibility: 'Detect payment, abandonment, subscription, and high-value risk signals.',
    inputs: ['payment attempts', 'customer context', 'checkout events'],
    outputs: ['structured findings'],
    tools: ['read_payment_attempts', 'read_customers'],
    permissions: ['payments:read', 'customers:read'],
    context: 'Merchant-scoped operational payment context.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'Return empty findings and mark fallback.',
    safetyLimits: ['Read-only', 'No action execution', 'Maximum 100 findings'],
    minimumConfidence: 0.6,
    promptVersion: 'detection.v1',
    outputSchema: detectionOutputSchema,
    fallback: empty(detectionOutputSchema),
  },
  diagnosis: {
    name: 'diagnosis',
    responsibility: 'Explain likely causes using supplied evidence.',
    inputs: ['detection findings', 'failure reasons'],
    outputs: ['evidence-backed diagnoses'],
    tools: ['read_payment_attempts'],
    permissions: ['payments:read'],
    context: 'Only supplied merchant evidence; no invented facts.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'Return no diagnosis rather than speculate.',
    safetyLimits: ['Evidence required', 'No customer mutation'],
    minimumConfidence: 0.7,
    promptVersion: 'diagnosis.v1',
    outputSchema: diagnosisOutputSchema,
    fallback: empty(diagnosisOutputSchema),
  },
  recovery: {
    name: 'recovery',
    responsibility: 'Recommend allowlisted recovery strategies.',
    inputs: ['diagnosis', 'risk assessments', 'policy context'],
    outputs: ['allowlisted recommendations'],
    tools: ['read_opportunities'],
    permissions: ['recovery:recommend', 'risk:read', 'policy:read'],
    context: 'Recommendation-only; deterministic services decide execution.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'Return no recommendation when evidence or confidence is insufficient.',
    safetyLimits: ['Allowlisted actions only', 'No provider calls', 'No arbitrary commands'],
    minimumConfidence: 0.8,
    promptVersion: 'recovery.v1',
    outputSchema: recoveryOutputSchema,
    fallback: empty(recoveryOutputSchema),
  },
  risk: {
    name: 'risk',
    responsibility: 'Assess risk and propose gate outcomes.',
    inputs: ['payment evidence', 'customer history', 'policy thresholds'],
    outputs: ['scored assessments'],
    tools: ['read_risk_assessments', 'read_policies'],
    permissions: ['risk:read', 'policy:read'],
    context: 'Risk output is advisory and must be checked deterministically.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'Fail closed with BLOCK decisions.',
    safetyLimits: ['Score 0-100', 'Evidence required', 'Cannot approve execution'],
    minimumConfidence: 0.9,
    promptVersion: 'risk.v1',
    outputSchema: riskOutputSchema,
    fallback: (_context, _reason) => ({ assessments: [], confidence: 0 }),
  },
  finance: {
    name: 'finance',
    responsibility: 'Summarize financial impact using verified decimal amounts.',
    inputs: ['ledger', 'payment', 'opportunity data'],
    outputs: ['financial summaries'],
    tools: ['read_ledger', 'read_payments'],
    permissions: ['finance:read'],
    context: 'Read-only accounting context.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'Return an unavailable summary.',
    safetyLimits: ['No ledger writes', 'No float-based calculation'],
    minimumConfidence: 0.9,
    promptVersion: 'finance.v1',
    outputSchema: financeOutputSchema,
    fallback: empty(financeOutputSchema),
  },
  escalation: {
    name: 'escalation',
    responsibility: 'Identify cases requiring human review.',
    inputs: ['risk decisions', 'policy results', 'recovery recommendations'],
    outputs: ['review requests'],
    tools: ['read_policies'],
    permissions: ['policy:read', 'approval:request'],
    context: 'Escalation only; cannot approve or execute.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'Escalate when uncertain.',
    safetyLimits: ['High-risk defaults to review', 'No automatic approval'],
    minimumConfidence: 0.8,
    promptVersion: 'escalation.v1',
    outputSchema: escalationOutputSchema,
    fallback: (_context, _reason) => ({ reviews: [], confidence: 0 }),
  },
  learning: {
    name: 'learning',
    responsibility: 'Extract bounded merchant-scoped observations from completed outcomes.',
    inputs: ['outcomes', 'audit evidence'],
    outputs: ['observations'],
    tools: ['read_audit_logs', 'write_merchant_memory'],
    permissions: ['audit:write', 'memory:read', 'memory:write'],
    context: 'Post-outcome learning only.',
    memoryAccess: 'merchant-scoped-write',
    failureBehavior: 'Discard observations that fail validation.',
    safetyLimits: ['No secrets', 'No cross-merchant data', 'No policy changes'],
    minimumConfidence: 0.85,
    promptVersion: 'learning.v1',
    outputSchema: learningOutputSchema,
    fallback: (_context, _reason) => ({ observations: [], confidence: 0 }),
  },
  merchant_copilot: {
    name: 'merchant_copilot',
    responsibility: 'Answer merchant questions with cited context and safe navigation suggestions.',
    inputs: ['merchant question', 'retrieved evidence'],
    outputs: ['cited answer'],
    tools: ['read_dashboard', 'read_audit_logs'],
    permissions: ['payments:read', 'finance:read', 'audit:write'],
    context: 'Merchant-scoped read assistant.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'State uncertainty and provide no action.',
    safetyLimits: ['No money movement', 'No arbitrary tool calls', 'Citations required'],
    minimumConfidence: 0.8,
    promptVersion: 'copilot.v1',
    outputSchema: copilotOutputSchema,
    fallback: (_context, _reason) => ({
      answer: 'I cannot provide a safe answer from the available evidence.',
      citations: [],
      suggestedActions: [],
      confidence: 0,
    }),
  },
  orchestrator: {
    name: 'orchestrator',
    responsibility:
      'Coordinate agent work while enforcing policy, risk, approval, and deterministic execution boundaries.',
    inputs: ['objective', 'merchant context'],
    outputs: ['gated workflow plan'],
    tools: ['run_allowed_agent'],
    permissions: ['policy:read', 'risk:read', 'approval:request'],
    context: 'Control-plane coordinator; never a financial executor.',
    memoryAccess: 'merchant-scoped-read',
    failureBehavior: 'Block the workflow on missing gates.',
    safetyLimits: [
      'Policy required',
      'Risk gate required',
      'Approval required when applicable',
      'Execution is never directly available',
    ],
    minimumConfidence: 1,
    promptVersion: 'orchestrator.v1',
    outputSchema: orchestratorOutputSchema,
    fallback: (_context, _reason) => ({
      objective: 'Blocked workflow',
      selectedAgents: [],
      policyCheckRequired: true,
      riskGateRequired: true,
      approvalRequired: true,
      executionAllowed: false,
      confidence: 1,
    }),
  },
};
